name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Cloning the repository
        uses: actions/checkout@v2

      - name: Installing node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing dependencies
        run: npm install

      - name: Linting code
        run: npm run lint

      - name: Building project
        run: npm run build